# Generated by Django 4.0.6 on 2022-07-22 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('fi_password', models.CharField(max_length=15)),
                ('se_password', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('is_tick', models.BooleanField(default=False, verbose_name='I Agree To The Terms and Conditions')),
                ('auth_token', models.CharField(default='l', max_length=50)),
                ('verified', models.CharField(default='false', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_email', models.EmailField(max_length=254)),
                ('blog_text', models.CharField(max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blogapp.registration')),
            ],
        ),
    ]
